name: ci

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write

    steps:
    - uses: actions/checkout@v4

    - name: Zip the mesh_to_pcd folder
      run: zip -r mesh_to_pcd.zip mesh_to_pcd

    - name: Upload the mesh_to_pcd.zip as a build artifact
      uses: actions/upload-artifact@v4
      with:
        name: mesh_to_pcd
        path: mesh_to_pcd.zip

    - name: Create a release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        files: mesh_to_pcd.zip